export const HIGHLIGHT = "HIGHLIGHT";
export const ADD_TO_PATTERN = "ADD_TO_PATTERN";
export const ADD_TO_CHOICE = "ADD_TO_CHOICE";
export const CHANGE_STATUS = "CHANGE_STATUS";
export const INCREMENT_COUNT = "INCREMENT_COUNT";
export const RESET_COUNT = "RESET_COUNT";